TG-128: Task form validations and React lazy
BaSP-m2022/alfonso-trackgenix-app pull request #43
Opened 2022-06-22 01:43 UTC by mpueblas

- Validations with Joi schema.
- React lazy working for a better perfomarnce.
- Absolute import for routes working.

2022-06-22 14:43 UTC, martinalbrnz reviewed
- validation messages are not working
- it's recommended to add a dropdown or a search to the parent project
- React lazy working fine

2022-06-22 14:55 UTC, nicolascostanza commented on src/Components/Tasks/AddTask/index.jsx
> +  console.log(errors);
console.log nop

2022-06-22 14:55 UTC, nicolascostanza commented on src/Components/Tasks/index.js
> +import * as projectThunks from 'redux/projects/thunks';
excelente

2022-06-22 14:55 UTC, nicolascostanza commented on src/Components/Tasks/index.js
> +        console.log(response);
este console.log no va

2022-06-22 23:24 UTC, mpueblas commented on src/Components/Tasks/AddTask/index.jsx
> +    }),
it doesnt have a string.empty becouse is an optional field / min message fixed

2022-06-22 23:25 UTC, mpueblas commented on src/Components/Tasks/AddTask/index.jsx
> +    console.log('data: ', data);
fixed

2022-06-22 23:25 UTC, mpueblas commented on src/Components/Tasks/AddTask/index.jsx
> +  console.log(errors);
fixed

2022-06-24 21:17 UTC, GinaSchP submitted a review, later dismissed

2022-06-24 22:52 UTC, martinalbrnz submitted a review, later dismissed
LGTM

2022-06-25 00:05 UTC, fernandocarbone1 submitted a review, later dismissed

2022-06-25 18:36 UTC, karu-ams requested changes
## TEST RESULTS ❗ 
Tested locally on _https://alfonso-trackgenix-nnp6l61zo-basp-m2022.vercel.app/_

**Test Results:** FAILED ⚠️ Bugs found

1. A load icon could be implemented so the "fetching..." is not seen by the user. This could be implemented too when the user entered in the edit form because the previuos data that has been charged is shown before the actual is load.
https://user-images.githubusercontent.com/101274200/175785973-8905944a-fd17-41c1-9b96-fbe86821c125.mp4

https://user-images.githubusercontent.com/101274200/175786108-08a80ad7-9c23-4b81-a844-9fcc25945a14.mp4

2. The validation of the inputs should be onblur to maintain consistency with the other entities.
![chrome-capture-2022-5-25](https://user-images.githubusercontent.com/101274200/175786253-17b1f74c-01d9-4cf7-9455-0a3ce5bafc26.gif)

3. As a suggestion: The form content in the modal could be centered, and status input could be the same size as the other ones.
![image](https://user-images.githubusercontent.com/101274200/175786285-60f11aa8-67fb-4276-95e7-beb523c49546.png)
![image](https://user-images.githubusercontent.com/101274200/175786352-3d3dcac5-41eb-4f09-b270-09ad0c277d61.png)

2022-06-25 19:47 UTC, karu-ams approved these changes
## TEST RESULTS
Tested locally on _https://alfonso-trackgenix-1v60jzbjl-basp-m2022.vercel.app/_

Test Results: PASS ✅ READY TO MERGE

2022-06-25 20:02 UTC, JuanBSantomero submitted a review, later dismissed
Everything looks great

2022-06-25 20:12 UTC, JuanBSantomero approved these changes

2022-06-25 20:14 UTC, FefeTroanes approved these changes
😎👉🏼

2022-06-25 20:14 UTC, merged