TG 71: add edit tasks
BaSP-m2022/alfonso-trackgenix-app pull request #8
Opened 2022-05-31 02:38 UTC by ilcosme

This is my request for merging to master branch. I worked with the tasks resource, making the necessary functions to add a new task and also to edit an existing task. I worked with 2 main components (add/edit) and the corresponding forms to fill the asked data.

2022-06-02 18:31 UTC, FefeTroanes reviewed
Te deje unas constultas fer, es sobre unos `console.log` nada mas

2022-06-02 18:31 UTC, FefeTroanes commented on src/Components/Tasks/AddTask/index.js
> +      console.log(data);
Este `console.log` lo dejaste a proposito fer? Porque si no creo que podria eliminarse

2022-06-02 18:31 UTC, FefeTroanes commented on src/Components/Tasks/EditTask/index.js
> +    console.log('Data:', data);
La misma consulta que antes

2022-06-02 19:45 UTC, fernandocarbone1 approved these changes

2022-06-02 19:45 UTC, fernandocarbone1 commented on src/Components/Tasks/AddTask/index.js
> +    } else if (res.status === 400 || res.status === 500) {
Sólo como comentario/sugerencia Fer: al tratarse de dos errores diferentes de status, tal vez el mensaje de alerta podría indicar si se trata de una mala petición o un problema del server (por ej:
return res.status(400).json({
message: error
});
Pero así como está, funciona igual. Por eso digo solo sugerencia.

2022-06-02 22:07 UTC, ilcosme commented on src/Components/Tasks/AddTask/index.js
> +    } else if (res.status === 400 || res.status === 500) {
Intente pero en las controladoras no habia casos para status 400, asi que lo deje asi

2022-06-02 22:14 UTC, ilcosme commented on src/Components/Tasks/EditTask/index.js
> +      console.log('Data:', data);
Listo tirri

2022-06-04 14:30 UTC, FlorenciaEusebi commented
## Test Results
Tested locally on alfonso-trackgenix-server.vercel.app

**Test Results: Failed** :warning:

Bugs found:
1. There are no buttons to add a task, edit a task or see existing tasks inside the Task Layout Section.

![TASKS Layout](https://user-images.githubusercontent.com/80362960/172006922-9d5ac092-8d04-4dd6-b18c-297cca682dae.JPG)

2. The input spaces inside the form should be centered.
![TASKS Form](https://user-images.githubusercontent.com/80362960/172006927-5a84ee5f-e17c-48f8-bda8-a0912d58513c.JPG)

3. The BACK button (both in ADD and EDIT sections) is not working, it leads to https://alfonso-trackgenix-server.vercel.app/tasks
4.  Only existing Tasks can be added as new.
5. Edit section could not be tested, the tester was not able to edit existing tasks.

2022-06-04 14:31 UTC, FlorenciaEusebi requested changes
Please refer to https://github.com/BaSP-m2022/alfonso-trackgenix-app/pull/8#issuecomment-1146623427

2022-06-05 21:28 UTC, martinalbrnz commented on public/index.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKN
Ojo que ya esta el link

2022-06-05 21:28 UTC, martinalbrnz commented on public/index.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKN
Ojo que ya esta el link x2

2022-06-05 21:41 UTC, martinalbrnz commented on src/Components/Tasks/List/Row/index.jsx
> +        <a href={`/tasks-edit/${id}`}>
try with 
`
<a href={`/tasks-edit?id=${id}`}>
`

2022-06-05 23:39 UTC, FlorenciaEusebi approved these changes

2022-06-06 00:03 UTC, merged